// French Training
train("L'Italie a été gouvernée pendant un an par un homme qui n'avait pas été élu par le peuple. Dès la nomination de Mario Monti au poste de président du conseil, fin 2011, j'avais dit :Attention, c'est prendre un risque politique majeur. Par leur vote, les Italiens n'ont pas seulement adressé un message à leurs élites nationales, ils ont voulu dire : Nous, le peuple, nous voulons garder la maîtrise de notre destin. Et ce message pourrait être envoyé par n'importe quel peuple européen, y compris le peuple français.", 'french');
train("Il en faut peu, parfois, pour passer du statut d'icône de la cause des femmes à celui de renégate. Lorsqu'elle a été nommée à la tête de Yahoo!, le 26 juillet 2012, Marissa Mayer était vue comme un modèle. Elle montrait qu'il était possible de perforer le fameux plafond de verre, même dans les bastions les mieux gardés du machisme (M du 28 juillet 2012). A 37 ans, cette brillante diplômée de Stanford, formée chez Google, faisait figure d'exemple dans la Silicon Valley californienne, où moins de 5 % des postes de direction sont occupés par des femmes. En quelques mois, le symbole a beaucoup perdu de sa puissance.", 'french');
train("Premier intervenant de taille à SXSW 2013, Bre Pettis, PDG de la société Makerbot, spécialisée dans la vente d'imprimantes 3D, a posé une question toute simple, avant de dévoiler un nouveau produit qui l'est un peu moins. Voulez-vous rejoindre notre environnement 3D ?, a-t-il demandé à la foule qui débordait de l'Exhibit Hall 5 du Convention Center.", 'french');
train("Des milliers de manifestants ont défilé samedi 9 mars à Tokyo pour exiger l'abandon rapide de l'énergie nucléaire au Japon, près de deux ans jour pour jour après le début de la catastrophe de Fukushima.", 'french');
train("Oui, ça en a tout l'air, même si le conflit en Syrie n'était pas confessionnel au départ et ne l'est pas encore vraiment. Il faut saluer là l'extraordinaire résistance de la société civile syrienne à la tentation confessionnelle, mais cela ne durera pas éternellement.", 'french');

// Spanish Training
train("El ex presidente sudafricano, Nelson Mandela, ha sido hospitalizado la tarde del sábado, según confirmó un hospital de Pretoria a CNN. Al parecer se trata de un chequeo médico que ya estaba previsto, relacionado con su avanzada edad, según explicó el portavoz de la presidencia Sudafricana Mac Maharaj.", 'spanish');
train("Trabajadores del Vaticano escalaron al techo de la Capilla Sixtina este sábado para instalar la chimenea de la que saldrá el humo negro o blanco para anunciar el resultado de las votaciones para elegir al nuevo papa.La chimenea es el primer signo visible al público de las preparaciones que se realizan en el interior de la capilla donde los cardenales católicos se reunirán a partir de este martes para el inicio del cónclave.", 'spanish');
train("La Junta Directiva del Consejo Nacional Electoral (CNE) efectuará hoy una sesión extraordinaria para definir la fecha de las elecciones presidenciales, después de que Nicolás Maduro fuera juramentado ayer Viernes presidente de la República por la Asamblea Nacional.", 'spanish');
train(" A 27 metros bajo el agua, la luz se vuelve de un azul profundo y nebuloso. Al salir de la oscuridad, tres bailarinas en tutú blanco estiran las piernas en la cubierta de un buque de guerra hundido. No es una aparición fantasmal, aunque lo parezca, es la primera de una serie de fotografías inolvidables que se muestran en la única galería submarina del mundo.", 'spanish');
train("Uhuru Kenyatta, hijo del líder fundador de Kenia, ganó por estrecho margen las elecciones presidenciales del país africano a pesar de enfrentar cargos de crímenes contra la humanidad por la violencia electoral de hace cinco años. Según anunció el sábado la comisión electoral, Kenyatta logró el 50,07% de los votos. Su principal rival, el primer ministro Raila Odinga, obtuvo 43,31% de los votos, y dijo que reclamará el resultado en los tribunales. La Constitución exige que el 50% más un voto para una victoria absoluta.", 'spanish');

// English Training
train("One morning in late September 2011, a group of American drones took off from an airstrip the C.I.A. had built in the remote southern expanse of Saudi Arabia. The drones crossed the border into Yemen, and were soon hovering over a group of trucks clustered in a desert patch of Jawf Province, a region of the impoverished country once renowned for breeding Arabian horses.", 'english');
train("Just months ago, demonstrators here and around Egypt were chanting for the end of military rule. But on Saturday, as a court ruling about a soccer riot set off angry mobs, many in the crowd here declared they now believed that a military coup might be the best hope to restore order. Although such calls are hardly universal and there is no threat of an imminent coup, the growing murmurs that military intervention may be the only solution to the collapse of public security can be heard across the country, especially in circles opposed to the Islamists who have dominated post-Mubarak elections. ", 'english');
train(" Syrian rebels released 21 detained United Nations peacekeepers to Jordanian forces on Saturday, ending a standoff that raised new tensions in the region and new questions about the fighters just as the United States and other Western nations were grappling over whether to arm them. The rebels announced the release of the Filipino peacekeepers, and Col. Arnulfo Burgos, a spokesman for the Armed Forces of the Philippines, confirmed it.", 'english');
train(" The 83rd International Motor Show, which opened here last week, features the world premieres of 130 vehicles. These include an unprecedented number of models with seven-figure prices, including the $1.3 million LaFerrari supercar, the $1.15 million McLaren P1, the $1.6 million Koenigsegg Hundra and a trust-fund-busting Lamborghini, the $4 million Veneno. The neighborhood has become so rich that the new Rolls-Royce Wraith, expected to sell for more than $300,000, seemed, in comparison, like a car for the masses.", 'english');
train("David Hallberg, the statuesque ballet star who is a principal dancer at both the storied Bolshoi Ballet of Moscow and American Ballet Theater in New York, is theoretically the type of front-row coup that warrants a fit of camera flashes. But when Mr. Hallberg, 30, showed up at New York Fashion Week last month, for a presentation by the Belgian designer Tim Coppens, he glided into the front row nearly unnoticed, save for a quick chat with Tumblr’s fashion evangelist, Valentine Uhovski, and a warm embrace from David Farber, the executive style editor at WSJ.", 'english');

// German Training
train("Fiat Chrysler muss einer Familie in den USA nach dem Unfalltod ihres vierjährigen Sohnes 150 Millionen Dollar Entschädigung zahlen. Der Auto-Hersteller sei für den Tod des Kindes im Jahr 2012 haftbar, urteilte die Jury eines Gerichts im US-Bundesstaat Georgia nach knapp zweiwöchiger Verhandlung. Das Unternehmen Chrysler, das mittlerweile zum Konzern Fiat Chrysler gehört, habe versäumt, Kunden davor zu warnen, dass es bei einem Auffahrunfall wegen des Benzintanks im hinteren Teil des Fahrzeugs eher zu einem Feuer kommen könne. Bei dem Unfall war ein Auto in den Chrysler aufgefahren und hatte dabei den Benzintank des Fahrzeugs aufgerissen. Daraufhin war der Wagen in Brand geraten. Das Kind wäre bei dem Unfall besser geschützt gewesen, wenn sich der Benzintank nicht so weit hinten im Wagen befunden hätte, hatte der Anwalt der Familie vor Gericht argumentiert.", 'german');
train("Rückblickend zeigt sich: Der Damm, der damals ein Loch bekam, ist inzwischen gebrochen. Die sieben Rednerpulte, die im itv-Studio von Salford bei Manchester am Donnerstagabend aufgebaut waren, symbolisieren den Wandel. Großbritannien steuert unaufhaltsam auf eine Politik wechselnder Koalitionen im kontinental-europäischen Stil zu. Sieben Kandidaten auf dramatisch dekorierter Bühne: Aufgereiht waren sie vor elektrisch-blauen Panelen unter schwertartig elektrisch-blauen Lichtstrahlen, die aus nachtschwarzem Hintergrund hervorstießen. Drei Frauen, vier Männer, vier Fragen: zur Wirtschaft, zur Immigration, zur Gesundheitspolitik und zur Zukunft für die Jugend des Landes. Zwei große, fünf kleinere Parteien. Die Plätze der Redner war wie die Reihenfolge ihrer Wortmeldungen ausgelost worden. Chaos hatten einige vorher prophezeit. Dank der brillanten Moderatorin Julie Etchingham entstand stattdessen ein wohl-choreografierter Reigen.", 'german');
train("Dennoch suchten bekannte Akteure der Friedensbewegung vor einigen Monaten die Nähe der umstrittenen Aktivisten, zumindest auf regionaler Ebene. Sie riefen etwa in Berlin gemeinsam mit ihnen zu den sogenannten Friedenswinter-Demonstrationen auf, die hauptsächlich auf die Ukraine-Politik der Bundesregierung abzielten. Ein Schritt, den einige bekannte Akteure schon damals kritisierten. Andere betonten, dass es dabei um die Menschen vor, nicht auf der Bühne ginge. Man wollte die Besucher der Demonstrationen erreichen, mit ihnen ins Gespräch kommen - nicht jedoch deren Organisatoren adeln. Das klappte allerdings nicht so recht. Auf der Friedenswinter-Demo in Berlin etwa trat Ken Jebsen zwar nicht als offizieller Redner auf, er fuhr jedoch auf einem Lautsprecher-Wagen mit und hielt seine Rede lautstark von dort.", 'german');
train("Alexis Tsipras war ein Jahr älter als damals Kohl, als er vor zwei Monaten zum Ministerpräsidenten von Griechenland gewählt wurde. Es ist nun eine schöne Osterbeschäftigung, sich zu überlegen, wie Kanzler Helmut Kohl mit dem jungen Tsipras, dem Regierungsnovizen, umgegangen wäre: Hätte er ihn, den Linken, mit Spott und Verachtung gestraft und gedemütigt? Hätte er väterliche Gefühle für ihn entwickelt? Wäre Kohl so herablassend gegenüber den Griechen, wie es die Vertreter der EU-Institutionen sind? Oder würde er, um Europa willen, so etwas wie eine Gebrechlichkeitspflegschaft für die Griechen übernehmen?", 'german');
train("Bis Ende Juni wird sich außerdem zeigen, ob in Amerika und Iran substantielle Zugeständnisse an die heimischen Kritiker notwendig sind. In Teheran scheint das derzeit weniger wahrscheinlich als in Washington, weil der religiöse Führer die Verhandlungen stützt. Präsident Obama hat es dagegen mit einer über den Verhandlungsgegenstand hinausgehenden Fundamentalkritik der Republikaner an seiner Außenpolitik zu tun. Sie dürften weiter versuchen, ihm im Kongress Steine in den Weg zu legen. Die starke verfassungsrechtliche Stellung des Präsidenten wird es seinen Gegnern allerdings schwer, wenn nicht sogar unmöglich machen, einen Vertragsabschluss mit Iran zu hintertreiben.", 'german');

// basque Training
train("Orain hiru urte, gaurko egunez topatu zuten Coollongatako erregearen zerraldoa. Bihotz taupada bakar batek eraman zuen 53 urteko gorputz mehe, ahul eta zargaldua, eta horrela, azken urteetan bakerik izan ez zuen buruak atseden hartu zuen. Michael Petersonen hileta 2012ko apirilaren bostean izan zen Tweed Headseko beilatokian. Bainujantzi, elastiko arrunt eta sandaliekin atonduta esan zioten agur Australiako olatuetan urrezko lorratza marraztu zuen gizonari.", 'basque');
train("Apirilaren 19an egingo du SORTZEN elkarteak zonalde diskriminatuan Euskaraz ikasi eta bizitzearen aldeko jaia. Aurten, Faltzesen izango da zita eta hainbat ekitaldi antolatu dituzte. Honetaz gain eragile sozialekin egindako aurkezpenean adierazi zuten bezala urteak dira Sortzen elkarteak, guraso eta bertako eragileekin batera, zonalde diskrimanatuko jaia antolatzen dutela. Aurten Faltzesen egokitu da jaia. Faltzesekoa 6. edizioa izanen da. Artoxoan hasi eta Larraga, Mendigorria, Villatuerta eta Aibarren ospatu ostean. Zonalde ez Vascofonoan, D ereduan haurrak matrikulatzeko beharra aldarrikatzetik sortu zen jai hau. Hainbat gurasoen eskariz.", 'basque');
train("1983ko abuztuan, sona handiko pertsekuzio baten ostean atxilotu zuten PT. Gibelean, hogei polizia-autoren sirenak lehertu beharrean, eta bera, beti bezala, kontrako norabidean zihoan, ziztu bizian, Brisbane ibaiari itzal egiten dion Story zubiko pasabidean, beste hamabost polizia-autoz osatutako barrikada batekin topo egin zuen arte. Hiru bider jarraian irabazi zuen Petersonek asteazkenean hasiko den Bell's Beacheko txapelketa (1973-1975). Zenbait egun beranduago egin zioten azken elkarrizketako azken galderan, lortutako emaitzarekin gustura al zegoen galdetu ziotenean, Brisbango zubian atxilotu ostean epailearen aurrean esan zituen hitz berberak errepikatu zituen: Merezi nuen.", 'basque');
train("Gazte Martxa Berriozarrera helduko da larunbat honetan Herria Mugarri lelopean Ernaik eta Aitzinak antolaturiko ekimenean. 2.000 gaztek ekin zioten bideari Lekunberritik ostiral goizean eta arratsaldean Irurtzunera iritsi ziren. Bertan, Euskal Herriko prozesu eratzailearen eta nazioarteko ordezkarien hitzaldiak, xamurtasun tailerra eta musikaz eta bertsoez gozatzeko aukera izan dute. Larunbat goizean abiatu dira Berriozarrerantz.Twitter bidez salatu dutenez, martxaren bukaera zihoazen zazpi gazte identifikatu egin ditu Guardia Zibilak. Bertan egingo dute ekitaldi nagusia, eta kontzertuek girotuko dute gaua: Skakeitan, Oliba Gorriak, Kop, Raperos de Emaus & Zero koma backing band, Mandoilek eta erromeria.", 'basque');
train("Komunikabideetara igorritako oharrean nabarmentzen dutenez, 73 herritan burutu dituzte herri batzar eta lan taldeetako saioak eta 3.771 lagunek parte hartu dute modu presentzialean. Ildo horretan, modu batera edo bestera 7.000 lagunek parte hartu dutela programen lanketan adierazi dute.Prozesu honen ondorioz, Gipuzkoako 73 herri kandidatura aurkeztuko dituzte eta irailaren 18an ekitaldia egingo dute Zarautzen zerrendak aurkezteko.", 'basque');

var testData = {};
testData.french  = "Plus de 200 personnes doivent assister, samedi 4 avril à l'Assemblée nationale, à la réunion du courant Repères écologistes, favorable à un retour des Verts au gouvernement. Les responsables présents à cette réunion pourraient amorcer la création d'un nouveau parti en-dehors d'Europe Ecologie-Les Verts";
testData.spanish = "La delegación de EE UU está encabezada por la secretaria de Estado para Latinoamérica, Roberta Jacobson, después de 35 años sin que un funcionario estadounidense de tan alto nivel visitara la isla. En tanto, la representación cubana será liderada por Josefina Vidal Ferreiro, directora para EE UU del Ministerio de Relaciones Exteriores.";
testData.english = "When Vladislav Revenok, an Orthodox priest, first participated in the obscure Russian version of Alaska’s Iditarod, he found himself in places so isolated that he was mobbed by villagers demanding to be baptized. They told him he was the first priest to visit the outback of the already remote Kamchatka Peninsula in about 50 years.";
testData.german  = "Frauen fühlen sich verkannt. Elfriede Jelinek hat wohlgemerkt nicht gesagt, dass man ihnen kein schönes Gedicht, keine nette wissenschaftliche Entdeckung zutraue. Sie hat vielmehr gemeint, dass man ihnen kein Lebenswerk zugesteht, keinen bedeutenden Beitrag zur menschlichen Zivilisation, für den das große männliche Genie gefeiert wird.";
testData.basque  = "Kartzelatik atera baino egun bat lehenago jakin zuten Oier Oaren senideek konfinatua izango dela. Kazeta.eus hedabideak jakinarazi duenez, Paris mendebaldean den Saint-Germain-en-Laye (Yvelines) herrian bizi beharko du. Aldi berean, egunean hiru aldiz izenpetu beharko du komisaldegian.";
